#!/bin/bash

##
# Upgrade everything, install salt minion, and connect to salt master
##
# This userdata script upgrades your system to the latest packages and
# installs and configures salt-minion to connect to the master. To user
# this script, you're expected to set the FQDN as your droplet name on
# DigitalOcean's control panel (Thus setting rDNS/PTR). You need to
# manually change the hostname (the human readable one) below. You also
# need to set the salt master's IP address below. After, just paste this
# script into the DigitalOcean creation page.
##
#
##


# Change to the desired hostname of your droplet (Human name, not FQDN).
hostname="<%HOSTNAME%>"
# Change to your saltstack master IP address (Private is prefered if you're in the same datacenter).
master="<%MASTER%>"


#### Don't edit below! ####

# Get the meta information from DigitalOcean
ip=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)
fqdn=$(curl -s http://169.254.169.254/metadata/v1/hostname)

# Set the hostname
echo "$hostname" > /etc/hostname
hostname -F /etc/hostname

# Create a temporary line in the hosts file that should get regenerated by the saltmaster.
echo "$ip $fqdn $hostname" >> /etc/hosts
cat /etc/hostname /etc/hosts

# Get all updates
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get autoremove --purge -y
apt-get autoclean

# Add the saltstack repository into sources.d
echo 'deb http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest trusty main' > /etc/apt/sources.list.d/saltstack.list

# Add the saltstack key into the APT keyring
curl https://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -

# Refresh package lists
apt-get update

# Install saltminion
apt-get install -y salt-minion

# Set the master IP in the minion configuration.
sed -i 's/#master: salt/master: '$master'/g' /etc/salt/minion

# Restart salt-minion
service salt-minion restart

# You're done!
exit 0
